version: '3'

services:
  java:
    build:
      context: ./sdks/java/
    container_name: java

  php:
    build:
      context: ./sdks/php/
    container_name: php
    depends_on:
      java:
        condition: service_completed_successfully

  python:
    build:
      context: ./sdks/python/
    container_name: python
    depends_on:
      php:
        condition: service_completed_successfully

  ruby:
    build:
      context: ./sdks/ruby/
    container_name: ruby
    depends_on:
      python:
        condition: service_completed_successfully
