version: '3'

services:
  java:
    build:
      context: ./sdks/java/
    container_name: java

  php:
    build:
      context: ./sdks/php/
    container_name: php

  python:
    build:
      context: ./sdks/python/
    container_name: python

  ruby:
    build:
      context: ./sdks/ruby/
    container_name: ruby
