export const mdTables: [
  string,
  { title?: string; htmlDescription?: string },
][] = [
  ["Voucher", {}],
  ["Campaign", {}],
  ["PromotionTier", {}],
  ["Reward", {}],
  ["RewardAssignment", {}],
  // ["PublicationsCreateResponseBody", {}],
  ["ValidationsValidateResponseBody", {}],
  ["Redemption", {}],
  ["RedemptionRollback", {}],
  ["RedemptionsRedeemResponseBody", {}],
  ["8_obj_loyalty_campaign_object", {}],
  ["8_obj_loyalty_card_object_non_expanded_categories", {}],
  ["EarningRule", {}],
  ["LoyaltyTier", {}],
  ["CustomerWithSummaryLoyaltyReferrals", {}],
  ["CustomerActivity", {}],
  ["OrderCalculated", {}],
  ["Product", {}],
  ["Sku", {}],
  ["ProductCollectionsItem", {}],
  ["ValidationRule", {}],
  ["ValidationRuleAssignment", {}],
  ["Segment", {}],
  ["EventsCreateRequestBody", {}],
  ["AsyncAction", {}],
  ["Export", {}],
  ["Category", {}],
  ["21_obj_metadata_schema_object", {}],
  ["Location", {}],
  ["QualificationsCheckEligibilityResponseBody", {}],
];
