export const mdTables: [string, string?][] = [
  ["Voucher", "VOUCHERS-API-Voucher-Object.md"],
  ["Campaign", "CAMPAIGNS-API-Campaign-Object.md"],
  ["PromotionTier", "PROMOTIONS-API-Promotion-Tier-Object.md"],
  ["Reward", "REWARDS-API-Reward-Object.md"],
  ["RewardAssignment", "REWARDS-API-Reward-Assignment-Object.md"],
  ["PublicationsCreateResponseBody", "PUBLICATIONS-API-Publication-Object.md"],
  ["VouchersValidateResponseBody", "VALIDATIONS-API-Validation-Object.md"],
  ["Redemption", "REDEMPTIONS-API-Redemption-Object.md"],
  ["RedemptionRollback", "REDEMPTIONS-API-Rollback-Redemption-Object.md"],
  [
    "RedemptionsRedeemResponseBody",
    "STACKABLE-DISCOUNTS-API-Stackable-Redemptions-Object.md",
  ],
  ["8_obj_loyalty_campaign_object", "LOYALTIES-API-Loyalty-Campaign-Object.md"],
  [
    "8_obj_loyalty_card_object_non_expanded_categories",
    "LOYALTIES-API-Loyalty-Card-Object.md",
  ],
  ["EarningRule", "LOYALTIES-API-Earning-Rule-Object.md"],
  ["LoyaltyTier", "LOYALTIES-API-Loyalty-Tier-Object.md"],
  ["CustomerResponse", "CUSTOMERS-API-Customer-Object.md"],
  ["CustomerActivity", "CUSTOMERS-API-Customer-Activity-Object.md"],
  ["OrderResponse", "ORDERS-API-Order-Object.md"],
  ["Product", "PRODUCTS-API-Product-Object.md"],
  ["Sku", "PRODUCTS-API-SKU-Object.md"],
  [
    "ProductsCollectionsItem",
    "PRODUCT-COLLECTIONS-API-Product-Collection-Object.md",
  ],
  ["ValidationRuleResponse", "VALIDATION-RULES-API-Validation-Rule-Object.md"],
  [
    "ValidationRuleAssignment",
    "VALIDATION-RULES-API-Validation-Rule-Assignment-Object.md",
  ],
  ["14_obj_segment_object", "SEGMENTS-API-Customer-Segment-Object.md"],
  ["TrackCustomEventRequestBody", "EVENTS-API-Custom-Event-Object.md"],
  ["18_res_list_consents_GET", "CONSENTS-API-Consents-Object.md"],
  ["17_obj_async_action_object", "ASYNC-ACTIONS-API-Async-Action-Object.md"],
  ["Export", "EXPORTS-API-Export-Object.md"],
  ["Category", "CATEGORIES-API-Category-Object.md"],
  [
    "21_obj_metadata_schema_object",
    "METADATA-SCHEMAS-API-Metadata-Schema-Object.md",
  ],
  ["22_obj_location_object", "LOCATIONS-API-Location-Object.md"],
  [
    "QualificationsCheckEligibilityResponseBody",
    "QUALIFICATIONS-API-Qualification-Object.md",
  ],
];
