export const mdTables: [
  string,
  { title?: string; htmlDescription?: string },
][] = [
  ["Voucher", { title: "Voucher Object" }],
  ["Campaign", { title: "Campaign Object" }],
  ["PromotionTier", { title: "Promotion Tier Object" }],
  ["Reward", { title: "Reward Object" }],
  ["RewardAssignment", { title: "Reward Assignment Object" }],
  ["PublicationsCreateResponseBody", { title: "Publication Object" }],
  ["ValidationsValidateResponseBody", { title: "Validation Object" }],
  ["Redemption", { title: "Redemption Object" }],
  ["RedemptionRollback", { title: "Redemption Rollback Object" }],
  ["RedemptionsRedeemResponseBody", { title: "Redemption Object" }],
  ["8_obj_loyalty_campaign_object", { title: "Loyalty Campaign Object" }],
  [
    "8_obj_loyalty_card_object_non_expanded_categories",
    { title: "Loyalty Card Object" },
  ],
  ["EarningRule", { title: "Earning Rule Object" }],
  ["LoyaltyTier", { title: "Loyalty Tier Object" }],
  ["CustomerWithSummaryLoyaltyReferrals", { title: "Customer Object" }],
  ["CustomerActivity", { title: "Customer Activity Object" }],
  ["OrderCalculated", { title: "Order Calculated Object" }],
  ["Product", { title: "Product Object" }],
  ["Sku", { title: "SKU Object" }],
  ["ProductCollectionsItem", { title: "Product Collection Object" }],
  ["ValidationRule", { title: "Validation Rule Object" }],
  ["ValidationRuleAssignment", { title: "Validation Rule Assignment Object" }],
  ["Segment", { title: "Segment Object" }],
  ["EventsCreateRequestBody", { title: "Event Object" }],
  ["AsyncAction", { title: "Async Action Object" }],
  ["Export", { title: "Export Object" }],
  ["Category", { title: "Category Object" }],
  ["21_obj_metadata_schema_object", { title: "Metadata Schema Object" }],
  ["Location", { title: "Location Object" }],
  [
    "QualificationsCheckEligibilityResponseBody",
    { title: "Qualification Object" },
  ],
];
