#!/bin/sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

export PATH="$PATH:/usr/local/bin:/opt/homebrew/bin"

if command -v npm >/dev/null 2>&1; then
    npm run pre-commit && git add .
else
    echo "Error: npm not found in PATH"
    exit 1
fi
