name: Sync OpenAPI definition to ReadMe

# Run workflow for every push to the `master` branch
on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      # Reduce VOUCHERS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /vouchers --method get --path /vouchers/{code} --method get --method post --method put --method delete --out OpenAPI-reduced-vouchers-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-vouchers-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce CAMPAIGNS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "CAMPAIGNS API" --out OpenAPI-reduced-campaigns-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-campaigns-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce PROMOTIONS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "PROMOTIONS API" --out OpenAPI-reduced-promotions-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-promotions-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce REWARDS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "REWARDS API" --out OpenAPI-reduced-rewards-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-rewards-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce DISTRIBUTIONS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "DISTRIBUTIONS API" --out OpenAPI-reduced-distributions-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-distributions-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce VALIDATIONS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "VALIDATIONS API" --out OpenAPI-reduced-validations-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-validations-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce REDEMPTIONS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "REDEMPTIONS API" --out OpenAPI-reduced-redemptions-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-redemptions-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce STACKABLE DISCOUNTS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "STACKABLE DISCOUNTS API" --out OpenAPI-reduced-stackable-discounts-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-stackable-discounts-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce LOYALTIES API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "LOYALTIES API" --out OpenAPI-reduced-loyalties-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-loyalties-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce CUSTOMERS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "CUSTOMERS API" --out OpenAPI-reduced-customers-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-customers-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce ORDERS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "ORDERS API" --out OpenAPI-reduced-orders-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-orders-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce PRODUCTS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "PRODUCTS API" --out OpenAPI-reduced-products-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-products-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce PRODUCT COLLECTIONS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "PRODUCT COLLECTIONS API" --out OpenAPI-reduced-product-collections-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-product-collections-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce VALIDATION RULES API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "VALIDATION RULES API" --out OpenAPI-reduced-validation-rules-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-validation-rules-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce SEGMENTS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "SEGMENTS API" --out OpenAPI-reduced-segments-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-segments-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce EVENTS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "EVENTS API" --out OpenAPI-reduced-events-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-events-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce CONSENTS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "CONSENTS API" --out OpenAPI-reduced-consents-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-consents-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce ASYNC ACTIONS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "ASYNC ACTIONS API" --out OpenAPI-reduced-async-actions-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-async-actions-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce EXPORTS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "EXPORTS API" --out OpenAPI-reduced-exports-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-exports-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce CATEGORIES API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "CATEGORIES API" --out OpenAPI-reduced-categories-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-categories-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # Reduce METADATA SCHEMAS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --tag "METADATA SCHEMAS API" --out OpenAPI-reduced-metadata-schemas-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-metadata-schemas-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      # First we're going to perform a dry run of syncing process.
      # We do this on every push to ensure that an actual sync will work properly
      - name: Sync docs to ReadMe (dry run)
        uses: ./
        with:
          rdme: docs ./docs/reference-docs --key=${{ secrets.README_API_KEY }} --version=${{ secrets.README_MAIN_VERSION }} --dryRun

      # And finally, we perform an actual sync to ReadMe if we're on the main branch
      - name: Sync docs to ReadMe
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
        uses: readmeio/rdme@8.3.0
        with:
          rdme: docs ./docs/reference-docs --key=${{ secrets.README_API_KEY }} --version=${{ secrets.README_MAIN_VERSION }}