name: Sync OpenAPI definition to ReadMe

# Run workflow for every push to the `master` branch
on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      # Find and replace categories with those stored in GitHub
      - name: Find and replace Categories for Reference Introduction Guides
      - uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "${{ secrets.API_CATEGORY_INTRODUCTION }}"
          replace: secrets.API_CATEGORY_INTRODUCTION

      # First we're going to perform a dry run of syncing process.
      # We do this on every push to ensure that an actual sync will work properly
      #- name: Sync docs to ReadMe (dry run)
      #  uses: readmeio/rdme@8.3.0
      #  with:
      #    rdme: docs ./docs --key=${{ secrets.README_API_KEY }} --version=${{ secrets.README_MAIN_VERSION }} --dryRun

      # And finally, we perform an actual sync to ReadMe if we're on the main branch
      #- name: Sync docs to ReadMe
      #  if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
      #  uses: readmeio/rdme@8.3.0
      #  with:
      #    rdme: docs ./docs --key=${{ secrets.README_API_KEY }} --version=${{ secrets.README_MAIN_VERSION }}