name: Sync OpenAPI definition to ReadMe

# Run workflow for every push to the `master` branch
on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      # First we're going to perform a dry run of syncing process.
      # We do this on every push to ensure that an actual sync will work properly
      #- name: Sync docs to ReadMe (dry run)
      #  uses: readmeio/rdme@8.3.0
      #  with:
      #    rdme: docs ./docs --key=${{ secrets.README_API_KEY }} --version=${{ secrets.README_MAIN_VERSION }} --dryRun

      # And finally, we perform an actual sync to ReadMe if we're on the main branch
      #- name: Sync docs to ReadMe
      #  if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
      #  uses: readmeio/rdme@8.3.0
      #  with:
      #    rdme: docs ./docs --key=${{ secrets.README_API_KEY }} --version=${{ secrets.README_MAIN_VERSION }}

      # Reduce VOUCHERS API
      - name: Reduce Vouchers API
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /vouchers --method get --path /vouchers/{code} --method get --method post --method put --method delete --path /vouchers/ --method post --path /vouchers/{code}/enable --method post --path /vouchers/{code}/disable --method post --path /vouchers/{code}/balance --method post --path /vouchers/import --method post --path /vouchers/importCSV --method post --path /vouchers/qualification --method post --path /vouchers/bulk/async --method post --path /vouchers/metadata/async --method post --path /vouchers/{code}/sessions/{sessionKey} --method delete --out OpenAPI-reduced-vouchers-api.json

      # Update VOUCHERS API title --> category name
      - name: Update Vouchers API category name
        run: |
          ls -l
          cat OpenAPI-reduced-vouchers-api.json
          ed OpenAPI-reduced-vouchers-api.json
          4i
          "title": "Vouchers API"
          .
          w
          q
          cat OpenAPI-reduced-vouchers-api.json
          
