name: Sync OpenAPI definition to ReadMe

# Run workflow for every push to the `master` branch
on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      # First we're going to perform a dry run of syncing process.
      # We do this on every push to ensure that an actual sync will work properly
      - name: Sync docs to ReadMe (dry run)
        uses: readmeio/rdme@8.3.0
        with:
          rdme: docs --key=${{ secrets.README_API_KEY }} --version=${{ secrets.README_MAIN_VERSION }} --dryRun

      # And finally, we perform an actual sync to ReadMe if we're on the main branch
      - name: Sync docs to ReadMe
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
        uses: readmeio/rdme@8.3.0
        with:
          rdme: docs --key=${{ secrets.README_API_KEY }} --version=${{ secrets.README_MAIN_VERSION }}

      # Reduce VOUCHERS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /vouchers --method get --path /vouchers/{code} --method get --method post --method put --method delete --path /vouchers/ --method post --path /vouchers/{code}/enable --method post --path /vouchers/{code}/disable --method post --path /vouchers/{code}/balance --method post --path /vouchers/import --method post --path /vouchers/importCSV --method post --path /vouchers/qualification --method post --path /vouchers/bulk/async --method post --path /vouchers/metadata/async --method post --path /vouchers/{code}/sessions/{sessionKey} --method delete --out OpenAPI-reduced-vouchers-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-vouchers-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.VOUCHERS_API_ID }}

      # Reduce CAMPAIGNS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /campaigns --method get --method post --path /campaigns/{campaignId} --method get --method put --method delete --path /campaigns/{campaignId}/vouchers --method post --path /campaigns/{campaignId}/vouchers/{code} --method post --path /campaigns/{campaignId}/import --method post --path /campaigns/{campaignId}/importCSV --method post --path /campaigns/qualification --method post --path /campaigns/{campaignId}/enable --method post --path /campaigns/{campaignId}/disable --method post --out OpenAPI-reduced-campaigns-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-campaigns-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.CAMPAIGNS_API_ID }}

      # Reduce PROMOTIONS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /promotions/tiers --method get --path /promotions/{campaignId}/tiers --method get --method post --path /promotions/tiers/{promotionTierId} --method put --method delete --path /promotions/tiers/{promotionTierId}/enable --method post --path /promotions/tiers/{promotionTierId}/disable --method post --path /promotions/{campaignId}/stacks --method get --method post --path /promotions/{campaignId}/stacks/{stackId} --method get --method put --method delete --out OpenAPI-reduced-promotions-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-promotions-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.PROMOTIONS_API_ID }}

      # Reduce REWARDS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /rewards --method get --method post --path /rewards/{rewardId} --method get --method put --method delete --path /rewards/{rewardId}/assignments --method get --method post --path /rewards/{rewardId}/assignments/{assignmentId} --method get --method put --method delete --out OpenAPI-reduced-rewards-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-rewards-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.REWARDS_API_ID }}

      # Reduce DISTRIBUTIONS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /publications --method get --method post --out OpenAPI-reduced-distributions-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-distributions-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.DISTRIBUTIONS_API_ID }}

      # Reduce VALIDATIONS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /vouchers/{code}/validate --method post --path /validate --method get --path /promotions/validation --method post --path /promotions/tiers/{tierId}/validation --method post --out OpenAPI-reduced-validations-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-validations-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.VALIDATIONS_API_ID }}

      # Reduce REDEMPTIONS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /redemptions --method get --path /redemptions/{redemptionId} --method get --path /vouchers/{code}/redemption --method get --method post --path /redeem --method post --path /redemptions/{redemptionId}/rollback --method post --path /promotions/tiers/{promotionTierId}/redemption --method post --out OpenAPI-reduced-redemptions-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-redemptions-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.REDEMPTIONS_API_ID }}

      # Reduce STACKABLE DISCOUNTS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /redemptions --method post --path /validations --method post --path /redemptions/{parentRedemptionId}/rollbacks --method post --out OpenAPI-reduced-stackable-discounts-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-stackable-discounts-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.STACKABLE_DISCOUNTS_API_ID }}

      # Reduce LOYALTIES API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /loyalties --method get --method post --path /loyalties/{campaignId} --method get --method put --method delete --path /loyalties/members/{memberId}/rewards --method get --path /loyalties/{campaignId}/reward-assignments/{assignmentId}/reward --method get --path /loyalties/{campaignId}/reward-assignments --method get --path /loyalties/{campaignId}/rewards --method get --method post --path /loyalties/{campaignId}/reward-assignments/{assignmentId} --method get --path /loyalties/{campaignId}/rewards/{assignmentId} --method get --method put --method delete --path /loyalties/{campaignId}/members/{memberId}/redemption --method post --path /loyalties/members/{memberId}/redemption --method post --path /loyalties/{campaignId}/earning-rules --method get --method post --path /loyalties/{campaignId}/earning-rules/{earningRuleId} --method get --method put --method delete --path /loyalties/{campaignId}/earning-rules/{earningRuleId}/enable --method post --path /loyalties/{campaignId}/earning-rules/{earningRuleId}/disable --method post --path /loyalties/{campaignId}/members --method get --method post --path /loyalties/{campaignId}/members/{memberId} --method get --path /loyalties/members/{memberId} --method get --path /loyalties/{campaignId}/members/{memberId}/balance --method post --path /loyalties/members/{memberId}/balance --method post --path /loyalties/{campaignId}/members/{memberId}/transfers --method post --path /loyalties/{campaignId}/members/{memberId}/activities --method get --path /loyalties/members/{memberId}/activities --method get --path /loyalties/{campaignId}/tiers --method get --path /loyalties/{campaignId}/tiers/{tierId} --method get --path /loyalties/members/{memberId}/tiers --method get --path /loyalties/{campaignId}/tiers/{tierId}/earning-rules --method get --path /loyalties/{campaignId}/tiers/{tierId}/rewards --method get --path /loyalties/{campaignId}/members/{memberId}/points-expiration --method get --path /loyalties/{campaignId}/points-expiration/export --method post --out OpenAPI-reduced-loyalties-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-loyalties-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.LOYALTIES_API_ID }}

      # Reduce CUSTOMERS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /customers --method get --method post --path /customers/{customerId} --method get --method put --method delete --path /customers/{customerId}/permanent-deletion --method post --path /customers/importCSV --method post --path /customers/bulk/async --method post --path /customers/metadata/async --method post --path /customers/{customerId}/consents --method put --path /customers/{customerId}/consents# --method put --path /customers/{customerId}/activities --method get --path /customers/{customerId}/segments --method get --out OpenAPI-reduced-customers-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-customers-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.CUSTOMERS_API_ID }}

      # Reduce ORDERS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /orders --method get --method post --path /orders/{orderId} --method get --method put --path /orders/import --method post --path /orders/export --method post --out OpenAPI-reduced-orders-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-orders-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.ORDERS_API_ID }}

      # Reduce PRODUCTS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /products --method get --method post --path /products/{productId} --method get --method put --method delete --path /products/bulk/async --method post --path /products/metadata/async --method post --path /skus/{skuId} --method get --path /products/{productId}/skus --method get --method post --path /products/{productId}/skus/{skuId} --method put --method delete --path /products/importCSV --method post --path /skus/importCSV --method post --out OpenAPI-reduced-products-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-products-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.PRODUCTS_API_ID }}

      # Reduce PRODUCT COLLECTIONS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /product-collections --method get --path /product-collections/{productCollectionId} --method get --method delete --path /product-collections/{productCollectionId}/products --method get --out OpenAPI-reduced-product-collections-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-product-collections-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.PRODUCT_COLLECTIONS_API_ID }}

      # Reduce VALIDATION RULES API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /validation-rules --method get --method post --path /validation-rules/{validationRuleId} --method get --method put --method delete --path /validation-rules-assignments --method get --path /validation-rules/{validationRuleId}/assignments --method get --method post --path /validation-rules/{validationRuleId}/assignments/{assignmentId} --method delete --out OpenAPI-reduced-validation-rules-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-validation-rules-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.VALIDATION_RULES_API_ID }}

      # Reduce SEGMENTS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /segments/{segmentId} --method get --method delete --path /segments --method post --out OpenAPI-reduced-segments-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-segments-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.SEGMENTS_API_ID }}

      # Reduce EVENTS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /events --method post --out OpenAPI-reduced-events-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-events-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.EVENTS_API_ID }}

      # Reduce CONSENTS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /consents --method get --path /consents# --method get --out OpenAPI-reduced-consents-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-consents-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.CONSENTS_API_ID }}

      # Reduce ASYNC ACTIONS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /async-actions --method get --path /async-actions/{asyncActionId} --method get --out OpenAPI-reduced-async-actions-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-async-actions-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.ASYNC_ACTIONS_API_ID }}

      # Reduce EXPORTS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /exports --method get --method post --path /exports/{exportId} --method get --method delete --path /exports/{export_Id} --method get --out OpenAPI-reduced-exports-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-exports-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.EXPORTS_API_ID }}

      # Reduce CATEGORIES API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /categories --method get --method post --path /categories/{categoryId} --method get --method put --method delete --out OpenAPI-reduced-categories-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-categories-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.CATEGORIES_API_ID }}

      # Reduce METADATA SCHEMAS API
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi:reduce ./reference/OpenAPI.json --path /metadata-schemas --method get --path /metadata-schemas/{resource} --method get --out OpenAPI-reduced-metadata-schemas-api.json

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: GitHub Action
        uses: readmeio/rdme@v8.3.0
        with:
          rdme: openapi OpenAPI-reduced-metadata-schemas-api.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.METADATA_SCHEMAS_API_ID }}
