name: Sync OpenAPI definition and Markdown docs to ReadMe

# Run workflow for every push to the `master` branch
on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      # Update API Reference Docs
      - name: Reduce Vouchers API
        uses: readmeio/rdme@v8.4.0
        with:
          rdme: openapi ./reference/OpenAPI.json --version=${{ secrets.README_MAIN_VERSION }} --update

       # First we're going to perform a dry run of syncing process.
       # We do this on every push to ensure that an actual sync will work properly
      - name: Sync docs to ReadMe (dry run)
        uses: readmeio/rdme@8.4.0
        with:
          rdme: docs ./docs --key=${{ secrets.README_API_KEY }} --version=${{ secrets.README_MAIN_VERSION }} --dryRun

      # And finally, we perform an actual sync to ReadMe if we're on the main branch
      - name: Sync docs to ReadMe
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
        uses: readmeio/rdme@8.4.0
        with:
          rdme: docs ./docs --key=${{ secrets.README_API_KEY }} --version=${{ secrets.README_MAIN_VERSION }}